### ISSUE TITLE
Ticket Creation error

### ISSUE THREAD

**Issue by vidhyasagarreddy** [mozts2005/ZendeskApi_v2#125]
Iam able to create ticket from my local machine. But when in production, it kicks me offs throwing: 
"System.NullReferenceException: Object reference not set to an instance of an object.   at ZendeskApi_v2.Core.RunRequest(String resource, String requestMethod, Object body)   at ZendeskApi_v2.Core.RunRequest[T](String resource, String requestMethod, Object body)   at ZendeskApi_v2.Core.GenericGet[T](String resource)   at ZendeskApi_v2.Requests.Users.SearchByEmail(String email) "

Someone was facing the same issue at: https://support.zendesk.com/hc/communities/public/posts/203456436--net-C-NullReferenceException

**Comment by StephenMP** [comment]
Via your stack trace, this does not appear to be an issue when creating a ticket, but rather, when searching for a user by email. The issue you link to has a different stack trace that shows the creation of the ticket causing the error.

Without seeing the code you are running or what configurations you have set in your production environment, we cannot attempt to reproduce this issue. Likely, this is due to some sort of configuration issue in your production environment if you are able to run it locally.

**Comment by mozts2005** [comment]
closing Issue as there has been no response to questions asked.
