### ISSUE TITLE
Missing field in ZendeskApi_v2.Models.Satisfaction.SatisfactionRating

### ISSUE THREAD

**Issue by ASGgregl** [mozts2005/ZendeskApi_v2#337]
Class is missing string field: Reason

Field Definition from Zendesk: https://developer.zendesk.com/rest_api/docs/core/satisfaction_ratings

Name: reason 
Type: string
Comment: The reason for a bad rating given by the requester in a follow-up question. Satisfaction reasons must be enabled

**Comment by rwjdk** [comment]
In order to write unit-tests for this then according to the API (https://developer.zendesk.com/rest_api/docs/core/satisfaction_ratings) the "Ask a follow-up question after a bad rating" option (https://support.zendesk.com/hc/en-us/articles/223152967#topic_t2m_c4b_rw) need to be enabled on the test account (+ Need to understand how the feature work).  

Assume this is OK.

Can also just add the field (no big deal) but would not feel good just adding it without seeing the thing in action.

**Comment by mozts2005** [comment]
@rwjdk  feel free to add the needed feature to the zendesk account.

**Comment by rwjdk** [comment]
Added Pull request on this
