### ISSUE TITLE
Do you support the new announced DDoS protection system?

### ISSUE THREAD

**Issue by MarcNil** [mozts2005/ZendeskApi_v2#366]
I recently I got an announcement from Zendesk saying they are rolling out a new DDoS protection system and they write "You need to update your API client to pass the hostname for the certificate it requests in the SSL negotiation."

So my question is, is this supported out of the box? or do I need to update my code somehow?

The announcement is here:
https://support.zendesk.com/hc/en-us/articles/360001781967-Zendesk-rolls-out-new-DDoS-protection-and-abuse-prevention-system

**Comment by mozts2005** [comment]
based on my read of what is changing you should be fine. I have opened a ticket WIth Zendesk to have them enable this option on the testing account for the project So that we can double check. 

If code changes required a major refractor will be required as it will mean a change to HTTPClient.  

I will not know until we can test.

**Comment by mozts2005** [comment]
Ok, zendesk has updated the project's account and other than the incremental export timeouts being more sensitive everything looks to be working.

**Comment by code-gezellig** [comment]
Hi Elizabeth.
I'm using 3.7.2 of the library. Do I need to update it to avoid any possible issues relating with protection system updates? Or my version is fine in terms of DDoS protection coming updates?
Thank you.
